#!/usr/bin/env sh
#
# Functions to manage git repositories

git_functions_usage() {
    echo -e "Usage:"
    echo -e "\t~$ export GIT_AUTHOR_NAME=<name>"
    echo -e "\t~$ export GIT_AUTHOR_EMAIL=<email>"
    echo -e "\t~$ export ACCESS_TOKEN=<github key>"
    echo -e "\t~$ . git-functions"
}

git_config_ident() {
    git config --global user.name "${GIT_AUTHOR_NAME}"
    git config --global user.email "${GIT_AUTHOR_EMAIL}"
}

git_commit_and_push() {
    OPTIONS=$(getopt -l "branch:,message:" -o "b:m:" -a -- "$@")
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
            -b|--branch)
                shift
                BRANCH=$1
                ;;
            -m|--message)
                shift
                COMMIT_MSG="$1"
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done
    git checkout -b "${BRANCH}"
    git commit -a -m "${COMMIT_MSG}"
    git push origin "${BRANCH}"
}

git_clone_and_checkout() {
    OPTIONS=$(getopt -l "repository:,revision:" -o "r:v:" -a -- "$@")
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
            -r|--repository)
                shift
                REPOSITORY=$1
                ;;
            -v|--revision)
                shift
                REVISION="$1"
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    echo "Cloning the Repository..."

    REPO_DIR=$(basename "${REPOSITORY}" .git)

    # rewrites the repo url with the auth token
    CLONE_URL="https://oauth2:${ACCESS_TOKEN}@${REPOSITORY#*://}"
    git clone --depth 1 --branch "${REVISION}" "${CLONE_URL}"
    cd "${REPO_DIR}"
}

git_rebase() {
    OPTIONS=$(getopt -l "name:,remote:,revision:" -o "n:r:v:" -a -- "$@")
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
            -n|--name)
                shift
                NAME=$1
                ;;
            -r|--remote)
                shift
                REMOTE=$1
                ;;
            -v|--revision)
                shift
                REVISION="$1"
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    # Rebase current branch with given upstream and branch.
    #
    # The endpoint should be authenticated and the remote
    # should have read access at least.
    git remote add "${NAME}" "https://oauth2:${ACCESS_TOKEN}@${REMOTE#*://}"
    git fetch "${NAME}" "${REVISION}"
    git rebase "${NAME}"/"${REVISION}"
}

git_push_with_retries() {
    OPTIONS=$(getopt -l "branch:,retries:,url:" -o "b:r:u:" -a -- "$@")
    eval set -- "$OPTIONS"
    while true; do
        case "$1" in
            -b|--branch)
                shift
                BRANCH=$1
                ;;
            -r|--retries)
                shift
                RETRIES=$1
                ;;
            -u|--url)
                shift
                URL=$1
                ;;
            --)
                shift
                break
                ;;
        esac
        shift
    done

    attempt=0
    until [ "$attempt" -gt "$RETRIES" ] ; do
      git push "$URL" && break
      attempt=$((attempt+1))
      git pull --rebase origin $BRANCH
    done
    if [ "$attempt" -gt "$RETRIES" ] ; then
      echo "Max retries exceeded."
      return 1
    fi
}

git_functions_init() {
  # an actual user should be set
  [ -z "${GIT_AUTHOR_NAME}" ] || [ -z "${GIT_AUTHOR_EMAIL}" ] && git_functions_usage && return 1

  # it should not continue if ACCESS_TOKEN
  [ -z "${ACCESS_TOKEN}" ] && git_functions_usage && return 1

  # set identity
  git_config_ident
}
