#!/bin/bash
#
# script:      translate-delivery-repo
# 
# description: This script translates repo references to the proper public registry references.
#              It turns registry.redhat.io/product/repo into registry.access.redhat.com/product/repo for production repos and
#              registry.stage.redhat.io/product/repo -> registry.access.stage.redhat.com/product/repo for stage repos. It outputs a
#              json string with two entries. Each entry is of the form repo: [redhat.io, access.redhat.com],
#              url: <translated-delivery-repo>. 
#
# example command:  
#              translate-delivery-repo REPO where REPO is registry.redhat.io/product/repo for example
#

REPO=$1

if [ -z "${REPO}" ]; then
    echo -e "Please pass a repo to translate like 'registry.redhat.io/product/repo'"
    exit 1
fi

case "${REPO}" in
  "registry.redhat.io/"*)
    IO_URL=${REPO}
    ACCESS_URL=${REPO/registry.redhat.io/registry.access.redhat.com}
    ;;
  "registry.stage.redhat.io/"*)
    IO_URL=${REPO}
    ACCESS_URL=${REPO/registry.stage.redhat.io/registry.access.stage.redhat.com}
    ;;
  *)
    echo -n "Warning: Repo to translate is not in expected format. Expected format is: registry.redhat.io/product/repo or registry.stage.redhat.io/product/repo" >&2
    IO_URL=$REPO
    ACCESS_URL=""
    ;;
esac

echo '[{"repo":"redhat.io","url":"'$IO_URL'"},{"repo":"access.redhat.com","url":"'$ACCESS_URL'"}]'
