#!/bin/bash
#
# script:      translate-delivery-repo
# 
# description: This script translates repo references to the proper public registry reference.
#              It turns quay.io/redhat-prod/product----repo into registry.redhat.io/product/repo for production repos and
#              quay.io/redhat-pending/product----repo -> registry.stage.redhat.io/product/repo for stage repos.
#
# example command:  
#              translate-delivery-repo REPO where REPO is quay.io/redhat-prod/product----repo for example
#

REPO=$1

if [ -z "${REPO}" ]; then
    echo -e "Please pass a repo to translate like 'quay.io/redhat-prod/product----repo'"
    exit 1
fi

if [[ "${REPO}" != "quay.io/redhat-prod"* && "${REPO}" != "quay.io/redhat-pending"* ]] ||
    [[ "${REPO}" != *"----"* ]] ; then
    echo -n "Warning: Repo to translate is not in expected format. Expected format is " >&2
    echo "quay.io/redhat-[prod,pending]/product----repo" >&2
fi

REPO=${REPO/quay.io\/redhat-prod/registry.redhat.io}
REPO=${REPO/quay.io\/redhat-pending/registry.stage.redhat.io}
REPO=${REPO//----//}

echo "${REPO}"
